name: Continuous Integration

on:
  push:
    branches:
      - '**'

env:
  REGISTRY: ghcr.io
  REPOSITORY: ${{ github.repository }}
  REGISTRY_USERNAME: ${{ github.actor }}

jobs:
  Build:
    name: Build & Delivery
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{secrets.TOKEN_GITHUB}}
          submodules: true

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        id: buildWithGradle
        run: ./gradlew clean build -x test
        shell: bash

      - name: Extract version
        run: |
          echo "VERSION=$(./gradlew -q getAppVersion)" >> ${GITHUB_ENV}

      - name: lowercase the image tag & repository
        run: |
          echo "REPOSITORY=$(echo $REPOSITORY | tr '[:upper:]' '[:lower:]')" >> ${GITHUB_ENV}

      - name: Set Spring Image Environment Variable
        run: |
          echo "SPRING_IMAGE=${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.VERSION }}" >> ${GITHUB_ENV}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ secrets.TOKEN_GITHUB }}

      - name: Build Image
        run: docker build --no-cache -t ${{ env.SPRING_IMAGE }} -f docker/Dockerfile .

      - name: Push
        run: docker push ${{ env.SPRING_IMAGE }}